const books = [
	{
		title: "O guia definitivo do mochileiro das galáxias",
		autor: "Douglas Adams",
		genre: "fantasy",
		publisher: "Arqueiro",
		language: "Português",
		pages: "784",
		publication: "17 de junho de 2013",
		translators:
			"Carlos Irineu da Costa, Leonardo Alves, Marcia Heloisa Amarante Gonçalves, Paulo Henriques Britto",
		ISBN: "9788580411737, 8580411734",
		dimensions: "23.6 x 16.2 x 4.4 cm",
		image:
			"https://images-na.ssl-images-amazon.com/images/I/51bJleesV-L._SY344_BO1,204,203,200_QL70_ML2_.jpg",
		price: 55.9,
		description:
			"COM INTRODUÇÃO INÉDITA DO AUTOR E PREFÁCIO DE NEIL GAIMAN \n OS CINCO LIVROS DA CULTUADA SÉRIE O MOCHILEIRO DAS GALÁXIAS REUNIDOS EM UM ÚNICO E DEFINITIVO VOLUME \n Com mais de 15 milhões de exemplares vendidos, a saga de Arthur Dent pela Galáxia conquistou fãs pelo mundo inteiro. O humor ácido e as tramas surreais de Douglas Adams se tornaram ícones de uma geração e seguem fascinando leitores de todas as idades. Reunindo todos os livros da série em uma edição de luxo, O Guia Definitivo do Mochileiro das Galáxias vai levar você por aventuras improváveis. Pegue sua toalha, divirta-se e não entre em pânico!",
	},
	{
		title: "O Hobbit",
		autor: "J.R.R. Tolkien",
		genre: "fantasy",
		publisher: "HarperCollins Brasil",
		language: "Português",
		pages: "336",
		publication: "15 de julho de 2019",
		translators: "Reinaldo José Lopes",
		ISBN: "9788595085800, 8595085803",
		dimensions: "21.2 x 14 x 2.4 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/91M9xPIf10L.jpg",
		price: 34.3,
		description:
			"Bilbo Bolseiro era um dos mais respeitáveis hobbits de todo o Condado até que, um dia, o mago Gandalf bate à sua porta. A partir de então, toda sua vida pacata e campestre soprando anéis de fumaça com seu belo cachimbo começa a mudar. Ele é convocado a participar de uma aventura por ninguém menos do que Thorin Escudo-de-Carvalho, um príncipe do poderoso povo dos Anãos. Essa jornada fará Bilbo, Gandalf e 13 anãos atravessarem a Terra-média, passando por inúmeros perigos, sejam eles, os imensos trols, as Montanhas Nevoentas infestadas de gobelins ou a muito antiga e misteriosa Trevamata, até chegarem (se conseguirem) na Montanha Solitária. Lá está um incalculável tesouro, mas há um porém. Deitado em cima dele está Smaug, o Dourado, um dragão malicioso que... bem, você terá que ler e desco...",
	},
	{
		title: "Fogo & Sangue - Volume 1",
		autor: "George R. R. Martin",
		genre: "fantasy",
		publisher: "Suma",
		language: "Português",
		pages: "664",
		publication: "20 de novembro de 2018",
		translators: "CLeonardo Alves, Regiane Winarski",
		ISBN: "9788554512941, 8554512944",
		dimensions: "23.6 x 16.2 x 4.4 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/818yNY0mMZL.jpg",
		price: 65.9,
		description:
			"Séculos antes dos eventos de A guerra dos tronos, a Casa Targaryen – única família de senhores dos dragões a sobreviver à Destruição de Valíria – tomou residência em Pedra do Dragão. A história de Fogo & Sangue começa com o lendário Aegon, o Conquistador, criador do Trono de Ferro, e segue narrando as gerações de Targaryen que lutaram para manter o assento, até a guerra civil que quase destruiu sua dinastia. \n O que realmente aconteceu durante a Dança dos Dragões? Por que era tão perigoso visitar Valíria depois da Destruição? Quais foram os piores crimes de Maegor, o Cruel? Essas são algumas das questões respondidas neste livro essencial, relatadas por um sábio meistre da Cidadela.",
	},
	{
		title: "Batman: Gotham Knights",
		autor: "A. J. Lieberman ",
		genre: "comic",
		publisher: "Planeta De Agostini",
		language: "Português",
		pages: "368",
		publication: "22 de novembro de 2022",
		translators: "L. Rizzi",
		ISBN: "9788467451863, 8467451866",
		dimensions: "17 x 0.1 x 26 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/61FM8F91qtL.jpg",
		price: 65.9,
		description:
			"Gilded City vai mostrar a cidade de Gotham no período de 1880, mostrando um vírus que foi desenvolvido durante essa época e que está retornando a cidade, e também vai mostrar um vigilante intitulado de Runaway que está investigando essa ameaça.",
	},
	{
		title: "Homem-Aranha: História de Vida",
		autor: "Chip Zdarsky",
		genre: "comic",
		publisher: "Panini",
		language: "Português",
		pages: "200",
		publication: "18 de fevereiro de 2021",
		translators: "Mateus Ornellas",
		ISBN: "9786555128741, 6555128747",
		dimensions: "26.6 x 17.2 x 1.2 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/412KPOUG9VL.jpg",
		price: 79.9,
		description:
			"Em Amazing Fantasy 15, de 1962, Peter Parker, um garoto de 15 anos, é picado por uma aranha irradiada e se torna o Espetacular Homem-Aranha! Cinquenta e oito anos se passaram no mundo real desde então — o que aconteceria se o mesmo tempo passasse para Peter? Chip Zdarsky e Mark Bagley se unem para uma abordagem única — contar a história da vida inteira do Homem-Aranha, com todos os eventos-chave das décadas em que ele viveu. Da Guerra do Vietnã, passando pelas Guerras Secretas e a Guerra Civil dos super-heróis, chegando ao que pode ser a última missão de um idoso Cabeça de Teia. Prepare-se para ver Peter Parker passar por décadas de história — e descubra o que acontece a ele e às pessoas mais importantes de sua vida!",
	},
	{
		title: "Os Vingadores: Vingadores Infinitos",
		autor: "Jonathan Hickman",
		genre: "comic",
		publisher: "Panini",
		language: "Português",
		pages: "784",
		publication: "17 de junho de 2013",
		translators: "Jonathan Hickman",
		ISBN: "9788580411737, 8580411734",
		dimensions: "23.6 x 16.2 x 4.4 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/91VesdekGwL.jpg",
		price: 55.9,
		description:
			"Lembra-se de quando os Illuminati apagaram sua própria existência da memória do Capitão América? Pois o Capitão também se lembra. Os Illuminati acirraram seus esforços para defender a Terra, mas a Sentinela da Liberdade os lembrará do preço de suas ações. E com a sobrevivência de todo o planeta Terra em risco, a Joia do Tempo ressurge e leva os Vingadores a uma perigosa jornada em direção ao futuro. Os Heróis Mais Poderosos da Terra viajam 50 5.000 50.000 anos no futuro e encaram o legado e as consequências de seus atos. o primeiro vingador encontra o último, o Mundo de Vingadores desaba, e você não vai acreditar no que vem a seguir. Este volume de 156 páginas reúne as edições 29 a 34 de Avengers, escritas por Jonathan Hickman e ilustradas por Leinil Francis Yu.",
	},
	{
		title: "Your Name Edição Única",
		autor: "Makoto Shinkai",
		genre: "manga",
		publisher: "JBC",
		language: "Português",
		pages: "496",
		publication: "23 de outubro de 2020",
		translators: "Ranmaru Kotone",
		ISBN: "8545713606, 978-8545713609",
		dimensions: "20 x 13.2 x 2.8 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/6175PH7eGwL.jpg",
		price: 55.9,
		description:
			"Edição única que reúne os três volumes do mangá baseado em Your Name., um dos filmes animados de maior sucesso da história do Japão.",
	},
	{
		title: "Boa Noite Punpun - Vol. 1",
		autor: "Inio Asano",
		genre: "manga",
		publisher: "JBC",
		language: "Português",
		pages: "432",
		publication: "15 de abril de 2022",
		translators: "Inio Asano",
		ISBN: "8545709617, 978-8545709619",
		dimensions: "20.07 x 13.21 x 2.79 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/51EQ5jMPsHL.jpg",
		price: 49.9,
		description:
			"Punpun Onodera é um garoto normal, que vive feliz com sua família. Um dia, Aiko Tanaka é transferida para a sua escola. Foi paixão à primeira vista!! Voltando juntos para casa, ela conta que no futuro, “a Terra vai se tornar um planeta inabitável”. É nessa hora que Punpun decide ser um cientista espacial. Porém, bem quando encontra seu objetivo na vida, a sua realidade começa a desmoronar. Considerado por muitos como a obra-prima do aclamado Inio Asano, Boa Noite Punpun é um slice of life que trata de temas delicados como solidão, relações familiares conturbadas e depressão.",
	},
	{
		title: "Chainsaw Man - 08",
		autor: "Tatsuki Fujimoto ",
		genre: "manga",
		publisher: "Panini",
		language: "Português",
		pages: "192",
		publication: "27 de maio de 2022",
		translators: "Tatsuki Fujimoto",
		ISBN: "6559602389, 978-6559602384",
		dimensions: "13.7 x 14.2 x 20 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/61Cl4931mUL.jpg",
		price: 29.9,
		description:
			"Enquanto Quanxi e as Divisões Especiais travam uma batalha por Denji, o sinistro Papai Noel começa a agir em prol de seu verdadeiro objetivo!! Mas quando um contrato perigoso repleto de maldade e insanidade é firmado, até mesmo os demônios ficam aterrorizados e as portas para um mundo de desespero se abrem! Os gritos do Demônio da Motosserra ecoarão pela noite escura feito breu!!",
	},
	{
		title: "O duque e eu (Os Bridgertons - Livro 1): O livro de Daphne",
		autor: "Julia Quinn ",
		genre: "romance",
		publisher: "Arqueiro",
		language: "Português",
		pages: "288",
		publication: "27 de maio de 2022",
		translators: "Cássia Zanon",
		ISBN: "8580411467, 978-8580411461",
		dimensions: "22.8 x 16 x 1.6 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/91N646H-kdL.jpg",
		price: 49.9,
		description:
			"Simon Basset, o irresistível duque de Hastings, acaba de retornar a Londres depois de seis anos viajando pelo mundo. Rico, bonito e solteiro, ele é um prato cheio para as mães da alta sociedade, que só pensam em arrumar um bom partido para suas filhas.",
	},
	{
		title: "A razão do amor",
		autor: "Ali Hazelwood  ",
		genre: "romance",
		publisher: "Arqueiro",
		language: "Português",
		pages: "336",
		publication: "10 de novembro de 2022",
		translators: "Raquel Zampil",
		ISBN: "655565399X, 978-6555653991",
		dimensions: "16 x 1.9 x 23 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/81P9aC6AckL.jpg",
		price: 54.9,
		description:
			"A carreira de Bee Königswasser está indo de mal a pior. Quando surge um processo seletivo para liderar um projeto de neuroengenharia da Nasa, ela se faz a pergunta que sempre guiou sua vida: o que Marie Curie faria? Participaria, é claro. Depois de conquistar a vaga, Bee descobre que precisará trabalhar com Levi Ward - um desafio que a mãe da física moderna nunca precisou enfrentar.",
	},
	{
		title: "A hipótese do amor",
		autor: "Ali Hazelwood  ",
		genre: "romance",
		publisher: "Arqueiro",
		language: "Português",
		pages: "336",
		publication: "5 de julho de 2022",
		translators: "Thaís Britto",
		ISBN: "6555653302, 978-6555653304",
		dimensions: "16 x 1.9 x 23 cm",
		image: "https://images-na.ssl-images-amazon.com/images/I/712x9dUpZFL.jpg",
		price: 54.9,
		description:
			"Olive Smith, aluna do doutorado em Biologia da Universidade Stanford, acredita na ciência - não em algo incontrolável como o amor.\nDepois de sair algumas vezes com Jeremy, ela percebe que sua melhor amiga gosta dele e decide juntá-los. Para mostrar que está feliz com essa escolha, Olive precisa ser convincente: afinal, cientistas exigem provas.",
	},
];

export default books;
